version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  api:
    build: ./api
    container_name: fullfood-api
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://host.docker.internal:11434
      - COLLECTION_NAME=recipes
      - EMBEDDING_MODELS=mxbai-embed-large,jina-embeddings-v2-base-es
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

volumes:
  qdrant_storage:
