global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fullfoodapp_api'
    metrics_path: /metrics
    static_configs:
      # macOS/Windows (Docker Desktop)
      - targets: ['host.docker.internal:8000']
        labels:
          service: fullfoodapp
      # Host local (si ejecutas Prometheus fuera de Docker o por compatibilidad)
      - targets: ['127.0.0.1:8000']
        labels:
          service: fullfoodapp
